name: Release Application
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # This token is used for interacting with the Git repo remote.
          token: ${{ secrets.ADMIN_PAT }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run NX Release
        env:
          # This token is used by nx release to create a GH Release with the GH API.
          GH_TOKEN: ${{ secrets.ADMIN_PAT }}
        run: |
          git config --global user.email "github.action@github.com"
          git config --global user.name "Github Action"
          npx nx release --verbose --skip-publish
