name: Release Application
on:
  workflow_dispatch:
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run NX Release
        run: |
          git config --global user.email "github.action@fxinnovation.com"
          git config --global user.name "Github Action"
          npx nx release --verbose --skip-publish
